FROM python:3.8-alpine

WORKDIR /app

RUN apk add --no-cache --virtual .build-deps \
    gcc \
    build-base \
    linux-headers \
    python3-dev \
    mariadb-dev \
    mariadb-connector-c-dev \
    libxml2-dev \
    libxslt-dev

ADD requirements.txt .
RUN  pip install --no-cache-dir -r requirements.txt

#RUN apk del .build-deps

COPY . .

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "main:app"]

